spring.application.name=stats_service

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/stats-service
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

server.port=9090

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

events.service.exchange=events.service.exchange
events.service.queue=events.service.queue
events.service.routing-key=stats.hit